name: Build PBF Glyphs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build PBF glyphs
        uses: linz/action-build-pbf-glyphs@v1
        with:
          source: fonts
          target: pbf
